from PyInstaller.utils.hooks import copy_metadata, collect_submodules, collect_data_files

datas = copy_metadata('traitsui')
datas += collect_data_files('traitsui', include_py_files=True)
hiddenimports = collect_submodules('traitsui')
hiddenimports += [
    'traitsui.wx.animated_gif_editor',
    'traitsui.wx.array_editor',
    'traitsui.wx.array_view_editor',
    'traitsui.wx.boolean_editor',
    'traitsui.wx.button_editor',
    'traitsui.wx.check_list_editor',
    'traitsui.wx.code_editor',
    'traitsui.wx.color_editor',
    'traitsui.wx.compound_editor',
    'traitsui.wx.csv_list_editor',
    'traitsui.wx.custom_editor',
    'traitsui.wx.data_frame_editor',
    'traitsui.wx.date_editor',
    'traitsui.wx.directory_editor',
    'traitsui.wx.dnd_editor',
    'traitsui.wx.drop_editor',
    'traitsui.wx.enum_editor',
    'traitsui.wx.file_editor',
    'traitsui.wx.font_editor',
    'traitsui.wx.history_editor',
    'traitsui.wx.html_editor',
    'traitsui.wx.image_editor',
    'traitsui.wx.image_enum_editor',
    'traitsui.wx.instance_editor',
    'traitsui.wx.key_binding_editor',
    'traitsui.wx.list_editor',
    'traitsui.wx.list_str_editor',
    'traitsui.wx.null_editor',
    'traitsui.wx.popup_editor',
    'traitsui.wx.progress_editor',
    'traitsui.wx.range_editor',
    'traitsui.wx.rgb_color_editor',
    'traitsui.wx.scrubber_editor',
    'traitsui.wx.search_editor',
    'traitsui.wx.set_editor',
    'traitsui.wx.shell_editor',
    'traitsui.wx.table_editor',
    'traitsui.wx.tabular_editor',
    'traitsui.wx.text_editor',
    'traitsui.wx.time_editor',
    'traitsui.wx.title_editor',
    'traitsui.wx.tree_editor',
    'traitsui.wx.tuple_editor',
    'traitsui.wx.ui_editor',
    'traitsui.wx.value_editor',
]
